# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a97b30f4d1e1229085d5ab90f71346b899bb507d0646d574dd75bbbbae1f8095c97ea76aeb9bb679705419347c04e1f710ebe4364b9443ff5dbe278ecdc41674

test:
  secret_key_base: fbc7804e606f09136dafd3bdeb867453452bbb8259f7f502670d4e08f1c902d2ff05577b469aaded3b94b4bfd1306712b090bfb1f51341f22fdf69f083a847cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
